//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho_ecommerce_teste
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoItens
    {
        public int PedidoItemId { get; set; }
        public int Quantidade { get; set; }
        public decimal PrecoUnitario { get; set; }
        public int PedidoId { get; set; }
        public int ProdutoId { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
